### PR TITLE
Migrate to Angular 4

### PR DESCRIPTION
**Pull request by rkaraivanov**

### CODE REVIEW

**Comment by JSMike** [comment]
FYI, this is throwing a lot of typescript errors when trying to build on windows.

**Comment by rkaraivanov** [comment]
@JSMike hmm, well that's strange as my dev machine is windows and it builds fine.
Do you have `tsc` globally installed and if so what version is it?

**Comment by JSMike** [comment]
I didn't have tsc installed globally, it's included in node_modules/.bin for the package. I tried installing globally with same result. global version is 1.5.3.

**Comment by kdinev** [comment]
@JSMike We're using version 2.2.2 and we don't see any errors.

**Comment by kdinev** [comment]
@JSMike We reproduced this on a different environment. We are looking into it.

**Comment by kdinev** [comment]
@JSMike We found the problem. Could you manually delete the typings folder? We will include a script that deletes it as well, because that's what messing the tsc up.

**Comment by JSMike** [comment]
Ok, yea I removed the global version. I was using the packaged version, 2.2.2, initially. I just tried the global version when @rkaraivanov asked.

FYI, removing the typings directory didn't solve the issue on it's own, you also need to update your tsconfig.json file to include the following inside compilerOptions:

```
    "typeRoots": [
      "node_modules/@types"
    ],
```

This resolved the issue for me.

**Pull request merged**
